export const FETCH_BUSINESS_RULES_REQUEST = "FETCH_BUSINESS_RULES_REQUEST";
export const FETCH_BUSINESS_RULES_SUCCESS = "FETCH_BUSINESS_RULES_SUCCESS";
export const FETCH_BUSINESS_RULES_FAILURE = "FETCH_BUSINESS_RULES_FAILURE";

export const DELETE_BUSINESS_RULE_REQUEST = "DELETE_BUSINESS_RULE_REQUEST";
export const DELETE_BUSINESS_RULE_OPTIMISTIC = "DELETE_BUSINESS_RULE_OPTIMISTIC";
export const DELETE_BUSINESS_RULE_SUCCESS = "DELETE_BUSINESS_RULE_SUCCESS";
export const DELETE_BUSINESS_RULE_FAILURE = "DELETE_BUSINESS_RULE_FAILURE";
