// WhatsApp Campaign Metrics
export const FETCH_WHATSAPP_METRICS_REQUEST = "FETCH_WHATSAPP_METRICS_REQUEST";
export const FETCH_WHATSAPP_METRICS_SUCCESS = "FETCH_WHATSAPP_METRICS_SUCCESS";
export const FETCH_WHATSAPP_METRICS_FAILURE = "FETCH_WHATSAPP_METRICS_FAILURE";
// 📋 Campaign List
export const CAMPAIGN_LIST_REQUEST = "CAMPAIGN_LIST_REQUEST";
export const CAMPAIGN_LIST_SUCCESS = "CAMPAIGN_LIST_SUCCESS";
export const CAMPAIGN_LIST_FAILURE = "CAMPAIGN_LIST_FAILURE";
export const CAMPAIGN_LIST_RESET   = "CAMPAIGN_LIST_RESET";

// 📋 Campaign Remove
export const CAMPAIGN_REMOVE_REQUEST = "CAMPAIGN_REMOVE_REQUEST";
export const CAMPAIGN_REMOVE_SUCCESS = "CAMPAIGN_REMOVE_SUCCESS";
export const CAMPAIGN_REMOVE_FAILURE = "CAMPAIGN_REMOVE_FAILURE";
export const CAMPAIGN_REMOVE_RESET   = "CAMPAIGN_REMOVE_RESET";

// 📧 Email Draft Approval
export const APPROVE_EMAIL_DRAFTS_REQUEST = "APPROVE_EMAIL_DRAFTS_REQUEST";
export const APPROVE_EMAIL_DRAFTS_SUCCESS = "APPROVE_EMAIL_DRAFTS_SUCCESS";
export const APPROVE_EMAIL_DRAFTS_FAILURE = "APPROVE_EMAIL_DRAFTS_FAILURE";
export const APPROVE_EMAIL_DRAFTS_RESET   = "APPROVE_EMAIL_DRAFTS_RESET";
