[
  { "label": "24-7 Media", "value": "24_7_media" },
  { "label": "Adform", "value": "adform" },
  { "label": "Adzerk", "value": "adzerk" },
  { "label": "Altitude ARENA", "value": "altitude_arena" },
  { "label": "Atlas by Facebook", "value": "atlas_by_facebook" },
  { "label": "DoubleClick", "value": "doubleclick" },
  { "label": "E-planning", "value": "e_planning" },
  { "label": "Emediate", "value": "emediate" },
  { "label": "Epom", "value": "epom" },
  { "label": "FreeWheel", "value": "freewheel" },
  { "label": "MicroAd", "value": "microad" },
  { "label": "Sizmek (MediaMind)", "value": "sizmek_mediamind" },
  { "label": "Smart AdServer", "value": "smart_adserver" },
  { "label": "Switch Concepts", "value": "switch_concepts" },
  { "label": "Weborama", "value": "weborama" },
  { "label": "3XChange", "value": "3xchange" },
  { "label": "41Ads", "value": "41ads" },
  { "label": "Ad Dynamo", "value": "ad_dynamo" },
  { "label": "Ad Unit 320 x 50", "value": "ad_unit_320_x_50" },
  { "label": "Adara", "value": "adara" },
  { "label": "Adconion", "value": "adconion" },
  { "label": "Adgoal", "value": "adgoal" },
  { "label": "Adition Technologies - Advertisers", "value": "adition_technologies_advertisers" },
  { "label": "AdParlor", "value": "adparlor" },
  { "label": "Advertising.com", "value": "advertising_com" },
  { "label": "Baidu Ads", "value": "baidu_ads" },
  { "label": "Bidtellect", "value": "bidtellect" },
  { "label": "Bing Ads", "value": "bing_ads" },
  { "label": "BlogHer", "value": "blogher" },
  { "label": "Boo-box", "value": "boo_box" },
  { "label": "Carbon", "value": "carbon" },
  { "label": "Chitika", "value": "chitika" },
  { "label": "Clicksor", "value": "clicksor" },
  { "label": "Collective Media", "value": "collective_media" },
  { "label": "Complex Media Network", "value": "complex_media_network" },
  { "label": "Conversant (ValueClick)", "value": "conversant_valueclick" },
  { "label": "CPMStar", "value": "cpmstar" },
  { "label": "CPX Interactive", "value": "cpx_interactive" },
  { "label": "Cross Pixel Media", "value": "cross_pixel_media" },
  { "label": "Datonics", "value": "datonics" },
  { "label": "DoubleClick Conversion", "value": "doubleclick_conversion" },
  { "label": "Dstillery", "value": "dstillery" },
  { "label": "Ezakus", "value": "ezakus" },
  { "label": "FederatedMedia", "value": "federatedmedia" },
  { "label": "Flashtalking", "value": "flashtalking" },
  { "label": "Flite", "value": "flite" },
  { "label": "Fluid Ads", "value": "fluid_ads" },
  { "label": "ForensIQ", "value": "forensiq" },
  { "label": "Glam Media", "value": "glam_media" },
  { "label": "Google AdSense", "value": "google_adsense" },
  { "label": "Google AdSense for Domains", "value": "google_adsense_for_domains" },
  { "label": "Google AdWords Conversion", "value": "google_adwords_conversion" },
  { "label": "Gorilla Nation", "value": "gorilla_nation" },
  { "label": "Gumgum", "value": "gumgum" },
  { "label": "HasOffers", "value": "hasoffers" },
  { "label": "Hi-Media Performance", "value": "hi_media_performance" },
  { "label": "IndustryBrains", "value": "industrybrains" },
  { "label": "Infolinks", "value": "infolinks" },
  { "label": "Integral Ad Science", "value": "integral_ad_science" },
  { "label": "Intent Media", "value": "intent_media" },
  { "label": "Interclick (Genome by Yahoo)", "value": "interclick_genome_by_yahoo" },
  { "label": "Kiosked", "value": "kiosked" },
  { "label": "Kontera", "value": "kontera" },
  { "label": "LifeStreet Media", "value": "lifestreet_media" },
  { "label": "Ligatus", "value": "ligatus" },
  { "label": "Linkedin Marketing Solutions", "value": "linkedin_marketing_solutions" },
  { "label": "MagnetVideo", "value": "magnetvideo" },
  { "label": "Marchex", "value": "marchex" },
  { "label": "MediaLets", "value": "medialets" },
  { "label": "Moat", "value": "moat" },
  { "label": "Onscroll", "value": "onscroll" },
  { "label": "OwnerIQ", "value": "owneriq" },
  { "label": "ProclivityMedia", "value": "proclivitymedia" },
  { "label": "Quartic", "value": "quartic" },
  { "label": "ReactX", "value": "reactx" },
  { "label": "redvertisement", "value": "redvertisement" },
  { "label": "Respond", "value": "respond" },
  { "label": "Right Media (Yahoo Ads)", "value": "right_media_yahoo_ads" },
  { "label": "Say Media", "value": "say_media" },
  { "label": "Scupio", "value": "scupio" },
  { "label": "SiteScout", "value": "sitescout" },
  { "label": "Specific Media", "value": "specific_media" },
  { "label": "Technorati", "value": "technorati" },
  { "label": "Tradedoubler", "value": "tradedoubler" },
  { "label": "TribalFusion", "value": "tribalfusion" },
  { "label": "TripleLift", "value": "triplelift" },
  { "label": "Twitter Advertising", "value": "twitter_advertising" },
  { "label": "Undertone", "value": "undertone" },
  { "label": "ValueClick Mediaplex", "value": "valueclick_mediaplex" },
  { "label": "Vibrant Media", "value": "vibrant_media" },
  { "label": "Viewable Media (Visable Measures)", "value": "viewable_media_visable_measures" },
  { "label": "WebSpectator", "value": "webspectator" },
  { "label": "Wider Planet", "value": "wider_planet" },
  { "label": "Yahoo Ad Manager", "value": "yahoo_ad_manager" },
  { "label": "YieldBot", "value": "yieldbot" },
  { "label": "Znaptag", "value": "znaptag" },
  { "label": "Basis", "value": "basis" },
  { "label": "Centro", "value": "centro" },
  { "label": "Groundtruth", "value": "groundtruth" },
  { "label": "AdBay", "value": "adbay" },
  { "label": "AdPilot", "value": "adpilot" },
  { "label": "Affiliate Window", "value": "affiliate_window" },
  { "label": "Affilinet", "value": "affilinet" },
  { "label": "Amazon Associates", "value": "amazon_associates" },
  { "label": "AvantLink", "value": "avantlink" },
  { "label": "Commission Junction", "value": "commission_junction" },
  { "label": "ContentClick", "value": "contentclick" },
  { "label": "Deqwas", "value": "deqwas" },
  { "label": "Impact Radius", "value": "impact_radius" },
  { "label": "Linkshare", "value": "linkshare" },
  { "label": "Opt-Intelligence", "value": "opt_intelligence" },
  { "label": "Postpresso", "value": "postpresso" },
  { "label": "RewardStyle", "value": "rewardstyle" },
  { "label": "ShareASale", "value": "shareasale" },
  { "label": "SkimLinks", "value": "skimlinks" },
  { "label": "Vantage Media", "value": "vantage_media" },
  { "label": "VigLink", "value": "viglink" },
  { "label": "Webgains", "value": "webgains" },
  { "label": "Yieldkit", "value": "yieldkit" },
  { "label": "Zanox", "value": "zanox" },

  { "label": "Adloox", "value": "adloox" },
  { "label": "AdMetrics", "value": "admetrics" },
  { "label": "Adometry (Google)", "value": "adometry_google" },
  { "label": "Alteryx", "value": "alteryx" },
  { "label": "Amplitude", "value": "amplitude" },
  { "label": "AT Internet", "value": "at_internet" },
  { "label": "AvantMetrics", "value": "avantmetrics" },
  { "label": "C3 Metrics", "value": "c3_metrics" },
  { "label": "Chartbeat", "value": "chartbeat" },
  { "label": "ClearSaleing (eBay Enterprise)", "value": "clearsaleing_ebay_enterprise" },
  { "label": "Clickdensity", "value": "clickdensity" },
  { "label": "ClickTale", "value": "clicktale" },
  { "label": "Clicky", "value": "clicky" },
  { "label": "Compete", "value": "compete" },
  { "label": "comScore", "value": "comscore" },
  { "label": "Convertro (AOL)", "value": "convertro_aol" },
  { "label": "Coremetrics", "value": "coremetrics" },
  { "label": "CrazyEgg", "value": "crazyegg" },
  { "label": "Databricks", "value": "databricks" },
  { "label": "DC Storm", "value": "dc_storm" },
  { "label": "Decibel Insight", "value": "decibel_insight" },
  { "label": "DemandBase", "value": "demandbase" },
  { "label": "Demandware Analytics", "value": "demandware_analytics" },
  { "label": "DeviceAtlas", "value": "deviceatlas" },
  { "label": "Drawbridge", "value": "drawbridge" },
  { "label": "Eaglestats", "value": "eaglestats" },
  { "label": "Econda", "value": "econda" },
  { "label": "Effective Measure", "value": "effective_measure" },
  { "label": "Etracker", "value": "etracker" },
  { "label": "eXTReMe Tracker", "value": "extreme_tracker" },
  { "label": "Facebook Conversion Tracking", "value": "facebook_conversion_tracking" },
  { "label": "Gauges", "value": "gauges" },
  { "label": "Google Analytics", "value": "google_analytics" },
  { "label": "GoSquared", "value": "gosquared" },
  { "label": "HeapAnalytics", "value": "heapanalytics" },
  { "label": "Histats", "value": "histats" },
  { "label": "Hitslink", "value": "hitslink" },
  { "label": "Hotjar", "value": "hotjar" },
  { "label": "IAPPS", "value": "iapps" },
  { "label": "InsightExpress", "value": "insightexpress" },
  { "label": "Improvely", "value": "improvely" },
  { "label": "InsightExpress Flex", "value": "insightexpress_flex" },
  { "label": "Inspectlet", "value": "inspectlet" },
  { "label": "Keen.io", "value": "keen_io" },
  { "label": "KISSmetrics", "value": "kissmetrics" },
  { "label": "KNIME", "value": "knime" },
  { "label": "Korrelate", "value": "korrelate" },
  { "label": "KYA", "value": "kya" },
  { "label": "Looker", "value": "looker" },
  { "label": "Lucky Orange", "value": "lucky_orange" },
  { "label": "Meetrics", "value": "meetrics" },
  { "label": "Mint", "value": "mint" },
  { "label": "Mixpanel", "value": "mixpanel" },
  { "label": "Motigo", "value": "motigo" },
  { "label": "MouseFlow", "value": "mouseflow" },
  { "label": "Nielsen NetRatings", "value": "nielsen_netratings" },
  { "label": "Omniture (Adobe)", "value": "omniture_adobe" },
  { "label": "OpenTracker", "value": "opentracker" },
  { "label": "Pathful", "value": "pathful" },
  { "label": "Performable", "value": "performable" },
  { "label": "PHG", "value": "phg" },
  { "label": "Piano Media", "value": "piano_media" },
  { "label": "Piwik", "value": "piwik" },
  { "label": "Pmetrics", "value": "pmetrics" },
  { "label": "Prudsys", "value": "prudsys" },
  { "label": "Quantcast", "value": "quantcast" },
  { "label": "Radarstats", "value": "radarstats" },
  { "label": "RealTracker", "value": "realtracker" },
  { "label": "Reinvigorate", "value": "reinvigorate" },
  { "label": "Segment.io", "value": "segment_io" },
  { "label": "SessionCam", "value": "sessioncam" },
  { "label": "ShinyStat", "value": "shinystat" },
  { "label": "Shop2Market", "value": "shop2market" },
  { "label": "Sisense", "value": "sisense" },
  { "label": "Data Analytics", "value": "data_analytics" },
  { "label": "SAP Analytics Cloud", "value": "sap_analytics_cloud" },
  { "label": "SiteMeter", "value": "sitemeter" },
  { "label": "Snoobi", "value": "snoobi" },
  { "label": "Sophus 3 eMetrics", "value": "sophus_3_emetrics" },
  { "label": "SpingMetrics", "value": "spingmetrics" },
  { "label": "Spinnakr", "value": "spinnakr" },
  { "label": "StatCounter", "value": "statcounter" },
  { "label": "SuperStats", "value": "superstats" },
  { "label": "Taboola Newsroom", "value": "taboola_newsroom" },
  { "label": "Tapad", "value": "tapad" },
  { "label": "Meta Pixel", "value": "meta_pixel" },
  { "label": "TeaLeaf", "value": "tealeaf" },
  { "label": "TopSpot", "value": "topspot" },
  { "label": "Totango", "value": "totango" },
  { "label": "trak.io", "value": "trak_io" },
  { "label": "Umbel", "value": "umbel" },
  { "label": "USERcycle", "value": "usercycle" },
  { "label": "Verint", "value": "verint" },
  { "label": "VisibleMeasures", "value": "visiblemeasures" },
  { "label": "Visual IQ", "value": "visual_iq" },
  { "label": "Visual Revenue", "value": "visual_revenue" },
  { "label": "W3Counter", "value": "w3counter" },
  { "label": "Walkme", "value": "walkme" },
  { "label": "Webtraxs", "value": "webtraxs" },
  { "label": "Webtrekk", "value": "webtrekk" },
  { "label": "Webtrends", "value": "webtrends" },
  { "label": "whos.amung.us", "value": "whos_amung_us" },
  { "label": "Woopra", "value": "woopra" },
  { "label": "Wowanalytics", "value": "wowanalytics" },
  { "label": "XiTi", "value": "xiti" },
  { "label": "Yahoo Analytics", "value": "yahoo_analytics" },
  { "label": "Yandex Metrica", "value": "yandex_metrica" },
  { "label": "Zift Solutions", "value": "zift_solutions" },

  { "label": "4PatientCare", "value": "4patientcare" },
  { "label": "AppointmentPlus", "value": "appointmentplus" },
  { "label": "AVImark Rapport", "value": "avimark_rapport" },
  { "label": "eCentral", "value": "ecentral" },
  { "label": "Front Desk Scheduling", "value": "front_desk_scheduling" },
  { "label": "Kicksite", "value": "kicksite" },
  { "label": "Mindbody", "value": "mindbody" },
  { "label": "Salon Ultimate", "value": "salon_ultimate" },
  { "label": "Schedulicity", "value": "schedulicity" },
  { "label": "Skedge.me", "value": "skedge_me" },
  { "label": "SolutionReach", "value": "solutionreach" },
  { "label": "SpeedRFP", "value": "speedrfp" },
  { "label": "STX Software", "value": "stx_software" },
  { "label": "TimeTrade", "value": "timetrade" },
  { "label": "Tula", "value": "tula" },
  { "label": "Vagaro", "value": "vagaro" },
  { "label": "Wodify", "value": "wodify" },
  { "label": "YouCanBook.me", "value": "youcanbook_me" },
  { "label": "Zen Planner", "value": "zen_planner" },
  { "label": "ZocDoc", "value": "zocdoc" },

  { "label": "Adobe Coldfusion", "value": "adobe_coldfusion" },
  { "label": "Adobe CQ", "value": "adobe_cq" },
  { "label": "Advanced Solutions International (ASi)", "value": "advanced_solutions_international_asi" },
  { "label": "Agility", "value": "agility" },
  { "label": "Atex", "value": "atex" },
  { "label": "Auctori", "value": "auctori" },
  { "label": "Auto Vitals", "value": "auto_vitals" },
  { "label": "BaseKit", "value": "basekit" },
  { "label": "Bitrix", "value": "bitrix" },
  { "label": "Blogger", "value": "blogger" },
  { "label": "BuddyPress", "value": "buddypress" },
  { "label": "Buuteeq", "value": "buuteeq" },
  { "label": "Catylist SiteLink", "value": "catylist_sitelink" },
  { "label": "Civic Plus", "value": "civic_plus" },
  { "label": "Clickability", "value": "clickability" },
  { "label": "ClickMotive", "value": "clickmotive" },
  { "label": "CM4All", "value": "cm4all" },
  { "label": "Cobalt", "value": "cobalt" },
  { "label": "Convio", "value": "convio" },
  { "label": "CrownPeak", "value": "crownpeak" },
  { "label": "Dealer.com", "value": "dealer_com" },
  { "label": "DealerOn", "value": "dealeron" },
  { "label": "DotNetNuke", "value": "dotnetnuke" },
  { "label": "DriverSide", "value": "driverside" },
  { "label": "Drupal", "value": "drupal" },
  { "label": "Ektron", "value": "ektron" },
  { "label": "EPiServer", "value": "episerver" },
  { "label": "Jazel", "value": "jazel" },
  { "label": "Jimdo", "value": "jimdo" },
  { "label": "Joomla", "value": "joomla" },
  { "label": "Kentico", "value": "kentico" },
  { "label": "Kirra", "value": "kirra" },
  { "label": "Kukui", "value": "kukui" },
  { "label": "Liferay", "value": "liferay" },
  { "label": "ListingLab", "value": "listinglab" },
  { "label": "LoopNet", "value": "loopnet" },
  { "label": "Magnolia", "value": "magnolia" },
  { "label": "Marqui", "value": "marqui" },
  { "label": "Microsoft Frontpage", "value": "microsoft_frontpage" },
  { "label": "Mono Solutions", "value": "mono_solutions" },
  { "label": "MyCase", "value": "mycase" },
  { "label": "NationBuilder", "value": "nationbuilder" },
  { "label": "NetSuite", "value": "netsuite" },
  { "label": "Oracle Webcenter", "value": "oracle_webcenter" },
  { "label": "Outsystems", "value": "outsystems" },
  { "label": "Pantheon", "value": "pantheon" },
  { "label": "PaperThin", "value": "paperthin" },
  { "label": "Placester", "value": "placester" },
  { "label": "SharePoint", "value": "sharepoint" },
  { "label": "SiteCore", "value": "sitecore" },
  { "label": "Squarespace", "value": "squarespace" },
  { "label": "Strikingly", "value": "strikingly" },
  { "label": "Tumblr", "value": "tumblr" },
  { "label": "TYPO3", "value": "typo3" },
  { "label": "vBulletin", "value": "vbulletin" },
  { "label": "WebCube", "value": "webcube" },
  { "label": "WebOffice", "value": "weboffice" },
  { "label": "Webydo", "value": "webydo" },
  { "label": "Weebly", "value": "weebly" },
  { "label": "Whipple Hill", "value": "whipple_hill" },
  { "label": "Wix", "value": "wix" },
  { "label": "Wordpress.com", "value": "wordpress_com" },
  { "label": "WordPress.org", "value": "wordpress_org" },
  { "label": "Wordpress VIP", "value": "wordpress_vip" },
  { "label": "WP Engine", "value": "wp_engine" },
  { "label": "Yext", "value": "yext" },
  { "label": "Yola", "value": "yola" },
  { "label": "YourMembership", "value": "yourmembership" },
  { "label": "Amcharts JS Library", "value": "amcharts_js_library" },
  { "label": "Backbone JS Library", "value": "backbone_js_library" },
  { "label": "Bootstrap Framework", "value": "bootstrap_framework" },
  { "label": "Bootstrap Framework v3.1.1", "value": "bootstrap_framework_v3_1_1" },
  { "label": "Bootstrap Framework v3.2.0", "value": "bootstrap_framework_v3_2_0" },
  { "label": "Ember JS Library", "value": "ember_js_library" },
  { "label": "Fusioncharts JS Library", "value": "fusioncharts_js_library" },
  { "label": "Highcharts JS Library", "value": "highcharts_js_library" },
  { "label": "JQuery 1.11.1", "value": "jquery_1_11_1" },
  { "label": "JQuery 2.1.1", "value": "jquery_2_1_1" },
  { "label": "React", "value": "react" },

  { "label": "CallRail", "value": "callrail" },
  { "label": "Century Interactive", "value": "century_interactive" },
  { "label": "Freespee", "value": "freespee" },
  { "label": "IfByPhone", "value": "ifbyphone" },
  { "label": "Infinity Tracking", "value": "infinity_tracking" },
  { "label": "LogMyCalls", "value": "logmycalls" },
  { "label": "ResponseTap", "value": "responsetap" },
  { "label": "Vox Analytics", "value": "vox_analytics" },

  { "label": "Keycaptcha", "value": "keycaptcha" },
  { "label": "Minteye / AdsCaptcha", "value": "minteye_adscaptcha" },
  { "label": "NLP Catpcha", "value": "nlp_catpcha" },
  { "label": "NuCaptcha", "value": "nucaptcha" },
  { "label": "reCAPTCHA", "value": "recaptcha" },
  { "label": "Solvemedia", "value": "solvemedia" },
  { "label": "sweetCaptcha", "value": "sweetcaptcha" },

  { "label": "Activa", "value": "activa" },
  { "label": "Activengage", "value": "activengage" },
  { "label": "ActiveTalk", "value": "activetalk" },
  { "label": "Apex Chat", "value": "apex_chat" },
  { "label": "BevyUp", "value": "bevyup" },
  { "label": "BoldChat", "value": "boldchat" },
  { "label": "Carchat24", "value": "carchat24" },
  { "label": "Cbox", "value": "cbox" },
  { "label": "Clientconnexion", "value": "clientconnexion" },
  { "label": "CloudIM", "value": "cloudim" },
  { "label": "Cobrowser Chat", "value": "cobrowser_chat" },
  { "label": "Comm100", "value": "comm100" },
  { "label": "Contactatonce", "value": "contactatonce" },
  { "label": "eGain", "value": "egain" },
  { "label": "Elead Chat", "value": "elead_chat" },
  { "label": "FordDirect Chat", "value": "forddirect_chat" },
  { "label": "Gaglers", "value": "gaglers" },
  { "label": "GoTalk", "value": "gotalk" },
  { "label": "GoToAssist (FASTchat)", "value": "gotoassist_fastchat" },
  { "label": "Gubagoo", "value": "gubagoo" },
  { "label": "HelpOnClick", "value": "helponclick" },
  { "label": "Iadvize", "value": "iadvize" },
  { "label": "InstantService", "value": "instantservice" },
  { "label": "JivoSite", "value": "jivosite" },
  { "label": "LiveChat", "value": "livechat" },
  { "label": "LivePerson Monitor", "value": "liveperson_monitor" },
  { "label": "LiveTex", "value": "livetex" },
  { "label": "LiveZilla", "value": "livezilla" },
  { "label": "Marva", "value": "marva" },
  { "label": "Moxie", "value": "moxie" },
  { "label": "Netop Live Guide", "value": "netop_live_guide" },
  { "label": "NetroxSC", "value": "netroxsc" },
  { "label": "Olark", "value": "olark" },
  { "label": "Onicon", "value": "onicon" },
  { "label": "OPanel", "value": "opanel" },
  { "label": "Oracle Live Help", "value": "oracle_live_help" },
  { "label": "P3chat", "value": "p3chat" },
  { "label": "ProvideSupport", "value": "providesupport" },
  { "label": "Pure Chat", "value": "pure_chat" },
  { "label": "PurpleView", "value": "purpleview" },
  { "label": "RealPerson Chat (Optimise-IT)", "value": "realperson_chat_optimise_it" },
  { "label": "RedHelper", "value": "redhelper" },
  { "label": "Robin", "value": "robin" },
  { "label": "Salesforce Live Agent", "value": "salesforce_live_agent" },
  { "label": "SalesMove", "value": "salesmove" },
  { "label": "SiteHeart", "value": "siteheart" },
  { "label": "SiteHelp", "value": "sitehelp" },
  { "label": "Slack", "value": "slack" },
  { "label": "Smartsupp", "value": "smartsupp" },
  { "label": "SnapEngage", "value": "snapengage" },
  { "label": "TouchCommerce", "value": "touchcommerce" },
  { "label": "Unblu", "value": "unblu" },
  { "label": "UserLike", "value": "userlike" },
  { "label": "Vee24", "value": "vee24" },
  { "label": "Velaro", "value": "velaro" },
  { "label": "Vivocha", "value": "vivocha" },
  { "label": "Volusion Livechat", "value": "volusion_livechat" },
  { "label": "WebGreeter", "value": "webgreeter" },
  { "label": "WebsiteAlive", "value": "websitealive" },
  { "label": "WhosOn", "value": "whoson" },
  { "label": "Zoho LiveDesk", "value": "zoho_livedesk" },
  { "label": "Zopim", "value": "zopim" },

  { "label": "Aircall", "value": "aircall" },
  { "label": "Cloudinary", "value": "cloudinary" },
  { "label": "Dialpad", "value": "dialpad" },
  { "label": "Dropbox", "value": "dropbox" },
  { "label": "Jumpcloud", "value": "jumpcloud" },
  { "label": "ServInt", "value": "servint" },
  { "label": "Google Workspace", "value": "google_workspace" },
  { "label": "Zoho One", "value": "zoho_one" },

  { "label": "CommentLuv", "value": "commentluv" },
  { "label": "Disqus", "value": "disqus" },
  { "label": "Facebook Comments", "value": "facebook_comments" },
  { "label": "Gigya Comments", "value": "gigya_comments" },
  { "label": "Intense Debate", "value": "intense_debate" },
  { "label": "Invision Power (IP Board)", "value": "invision_power_ip_board" },
  { "label": "LiveFyre", "value": "livefyre" },
  { "label": "SezWho", "value": "sezwho" },
  { "label": "Vanilla Forums", "value": "vanilla_forums" },
  { "label": "Viafoura", "value": "viafoura" },
  { "label": "Akamai", "value": "akamai" },
  { "label": "Amazon CloudFront", "value": "amazon_cloudfront" },
  { "label": "Amazon S3", "value": "amazon_s3" },
  { "label": "Amplience", "value": "amplience" },
  { "label": "Ananke CDN", "value": "ananke_cdn" },
  { "label": "Azure CDN", "value": "azure_cdn" },
  { "label": "BitGravity", "value": "bitgravity" },
  { "label": "Bitrix CDN", "value": "bitrix_cdn" },
  { "label": "Cachefly", "value": "cachefly" },
  { "label": "CDN77", "value": "cdn77" },
  { "label": "CDNetworks", "value": "cdnetworks" },
  { "label": "CDNsun", "value": "cdnsun" },
  { "label": "CDNVideo", "value": "cdnvideo" },
  { "label": "Cedexis", "value": "cedexis" },
  { "label": "China Net Center", "value": "china_net_center" },
  { "label": "ChinaCache", "value": "chinacache" },
  { "label": "CloudFlare CDN", "value": "cloudflare_cdn" },
  { "label": "Contentful", "value": "contentful" },
  { "label": "Distrify", "value": "distrify" },
  { "label": "DistroScale", "value": "distroscale" },
  { "label": "EdgeCast", "value": "edgecast" },
  { "label": "Fastly CDN", "value": "fastly_cdn" },
  { "label": "Google Cloud Storage", "value": "google_cloud_storage" },
  { "label": "Highwinds", "value": "highwinds" },
  { "label": "IELO", "value": "ielo" },
  { "label": "Instart Logic", "value": "instart_logic" },
  { "label": "Internap", "value": "internap" },
  { "label": "Internap CDN", "value": "internap_cdn" },
  { "label": "ISPrime", "value": "isprime" },
  { "label": "Level 3", "value": "level_3" },

  { "label": "Limelight", "value": "limelight" },
  { "label": "MaxCDN", "value": "maxcdn" },
  { "label": "Ngenix", "value": "ngenix" },
  { "label": "OnApp", "value": "onapp" },
  { "label": "Panther", "value": "panther" },
  { "label": "PubNub", "value": "pubnub" },
  { "label": "Pusher", "value": "pusher" },
  { "label": "RackSpace CDN", "value": "rackspace_cdn" },
  { "label": "Reflected Networks", "value": "reflected_networks" },
  { "label": "ScaleEngine", "value": "scaleengine" },
  { "label": "Skypark CDN", "value": "skypark_cdn" },
  { "label": "SwiftCDN", "value": "swiftcdn" },
  { "label": "Taobao", "value": "taobao" },
  { "label": "Tencent", "value": "tencent" },
  { "label": "TurboBytes", "value": "turbobytes" },
  { "label": "VHX", "value": "vhx" },
  { "label": "Xinnet", "value": "xinnet" },
  { "label": "Yekra", "value": "yekra" },
  { "label": "Yottaa", "value": "yottaa" },

  { "label": "AdBlade Advertisement", "value": "adblade_advertisement" },
  { "label": "AdBlade Tracking", "value": "adblade_tracking" },
  { "label": "Content.ad", "value": "content_ad" },
  { "label": "Dianomi", "value": "dianomi" },
  { "label": "Flix Media", "value": "flix_media" },
  { "label": "Gravity", "value": "gravity" },
  { "label": "Instinctive Ads", "value": "instinctive_ads" },
  { "label": "LinkSmart", "value": "linksmart" },
  { "label": "Native Ads", "value": "native_ads" },
  { "label": "NewsCred", "value": "newscred" },
  { "label": "Nster", "value": "nster" },
  { "label": "NTENT", "value": "ntent" },
  { "label": "Outbrain", "value": "outbrain" },
  { "label": "Outbrain - Advertisers", "value": "outbrain_advertisers" },
  { "label": "Perfect Market (Taboola)", "value": "perfect_market_taboola" },
  { "label": "Plista", "value": "plista" },
  { "label": "RealGravity", "value": "realgravity" },
  { "label": "Shareaholic Content Amplification", "value": "shareaholic_content_amplification" },
  { "label": "SimpleReach", "value": "simplereach" },
  { "label": "Taboola", "value": "taboola" },
  { "label": "Vidible", "value": "vidible" },
  { "label": "WebCollage", "value": "webcollage" },
  { "label": "Yahoo Recommends", "value": "yahoo_recommends" },
  { "label": "Zemanta", "value": "zemanta" },
  { "label": "Zergnet", "value": "zergnet" },

  { "label": "AthenaHealth", "value": "athenahealth" },
  { "label": "Avectra", "value": "avectra" },
  { "label": "Base CRM", "value": "base_crm" },
  { "label": "Blackbaud", "value": "blackbaud" },
  { "label": "Contact Center Solution", "value": "contact_center_solution" },
  { "label": "Gingr", "value": "gingr" },
  { "label": "InfusionSoft", "value": "infusionsoft" },
  { "label": "Insightly", "value": "insightly" },
  { "label": "Jive", "value": "jive" },
  { "label": "Lithium Technologies", "value": "lithium_technologies" },
  { "label": "Nimble AMS", "value": "nimble_ams" },
  { "label": "Ontraport", "value": "ontraport" },
  { "label": "Sage CRM", "value": "sage_crm" },
  { "label": "Salesforce", "value": "salesforce" },
  { "label": "Dynamics 365 CRM", "value": "dynamics_365_crm" },
  { "label": "Sugar CRM", "value": "sugar_crm" },
  { "label": "Telligent", "value": "telligent" },
  { "label": "Zoho CRM", "value": "zoho_crm" },
  { "label": "Ausgezeichnet", "value": "ausgezeichnet" },
  { "label": "Avis Verifies", "value": "avis_verifies" },
  { "label": "Bazaarvoice", "value": "bazaarvoice" },
  { "label": "Bizrate", "value": "bizrate" },
  { "label": "Demandforce Reviews Widget", "value": "demandforce_reviews_widget" },
  { "label": "Ekomi", "value": "ekomi" },
  { "label": "FeeFo", "value": "feefo" },
  { "label": "Fia-net", "value": "fia_net" },
  { "label": "Foxrate", "value": "foxrate" },
  { "label": "Guild Quality", "value": "guild_quality" },
  { "label": "Kiyoh.nl", "value": "kiyoh_nl" },
  { "label": "PowerReviews", "value": "powerreviews" },
  { "label": "PriceGrabber", "value": "pricegrabber" },
  { "label": "Reevoo", "value": "reevoo" },
  { "label": "ResellerRatings", "value": "resellerratings" },
  { "label": "Review Buzz", "value": "review_buzz" },
  { "label": "ReviewCentre", "value": "reviewcentre" },
  { "label": "Reviews.co.uk", "value": "reviews_co_uk" },
  { "label": "Shopauskunft", "value": "shopauskunft" },
  { "label": "Shopper Approved", "value": "shopper_approved" },
  { "label": "ShopVote", "value": "shopvote" },
  { "label": "The Feedback Company", "value": "the_feedback_company" },
  { "label": "TrustedShops", "value": "trustedshops" },
  { "label": "Trustpilot", "value": "trustpilot" },

  { "label": "Acxiom", "value": "acxiom" },
  { "label": "AudienceScience", "value": "audiencescience" },
  { "label": "Blueconic", "value": "blueconic" },
  { "label": "Bluekai", "value": "bluekai" },
  { "label": "Brilig", "value": "brilig" },
  { "label": "Crowd Science", "value": "crowd_science" },
  { "label": "DataLogix", "value": "datalogix" },
  { "label": "Enreach", "value": "enreach" },
  { "label": "Flxone", "value": "flxone" },
  { "label": "Krux", "value": "krux" },
  { "label": "LiveRamp", "value": "liveramp" },
  { "label": "LiveRamp Match Partners", "value": "liveramp_match_partners" },
  { "label": "Lotame", "value": "lotame" },
  { "label": "Navegg", "value": "navegg" },
  { "label": "Nielsen Display Ads (Formerly eXelate)", "value": "nielsen_display_ads_formerly_exelate" },
  { "label": "NuggAd", "value": "nuggad" },
  { "label": "Snowflake", "value": "snowflake" },
  { "label": "Microsoft Sql Server", "value": "microsoft_sql_server" },
  { "label": "Sojern", "value": "sojern" },
  { "label": "Stitch", "value": "stitch" },
  { "label": "TailTarget", "value": "tailtarget" },
  { "label": "Zencoder", "value": "zencoder" },

  { "label": "Ab Initio", "value": "ab_initio" },
  { "label": "33Across", "value": "33across" },
  { "label": "AppNexus", "value": "appnexus" },
  { "label": "DataXu", "value": "dataxu" },
  { "label": "FreakOut", "value": "freakout" },
  { "label": "GDM Digital", "value": "gdm_digital" },
  { "label": "GenesisMedia", "value": "genesismedia" },
  { "label": "MediaMath", "value": "mediamath" },
  { "label": "RocketFuel", "value": "rocketfuel" },
  { "label": "Simpli.fi", "value": "simpli_fi" },
  { "label": "The Trade Desk", "value": "the_trade_desk" },
  { "label": "Tradelab", "value": "tradelab" },
  { "label": "Triggit", "value": "triggit" },
  { "label": "Turn", "value": "turn" },
  { "label": "Yahoo Ad Manager Plus", "value": "yahoo_ad_manager_plus" },

  { "label": "123-reg DNS", "value": "123_reg_dns" },
  { "label": "Akamai DNS", "value": "akamai_dns" },
  { "label": "AT&T DNS", "value": "at_t_dns" },
  { "label": "Binero", "value": "binero" },
  { "label": "Cloudflare DNS", "value": "cloudflare_dns" },
  { "label": "Cotendo", "value": "cotendo" },
  { "label": "CSC Corporate Domains", "value": "csc_corporate_domains" },
  { "label": "DNS2Go", "value": "dns2go" },
  { "label": "DNS.com", "value": "dns_com" },
  { "label": "DNS Made Easy", "value": "dns_made_easy" },
  { "label": "DNSimple", "value": "dnsimple" },
  { "label": "DNSMax", "value": "dnsmax" },
  { "label": "DNSPark", "value": "dnspark" },
  { "label": "DNSPod", "value": "dnspod" },
  { "label": "DtDNS", "value": "dtdns" },
  { "label": "Dyn Managed DNS", "value": "dyn_managed_dns" },
  { "label": "DynIP", "value": "dynip" },
  { "label": "EasyDNS", "value": "easydns" },
  { "label": "EdgeDirector", "value": "edgedirector" },
  { "label": "Enom", "value": "enom" },
  { "label": "Fasthosts", "value": "fasthosts" },
  { "label": "Frobbit", "value": "frobbit" },
  { "label": "Google Cloud DNS", "value": "google_cloud_dns" },
  { "label": "Infoblox", "value": "infoblox" },
  { "label": "Internap DNS", "value": "internap_dns" },
  { "label": "LoadDNS", "value": "loaddns" },
  { "label": "Melbourne IT", "value": "melbourne_it" },
  { "label": "Netnames Cedel", "value": "netnames_cedel" },
  { "label": "Netnames Speednames", "value": "netnames_speednames" },
  { "label": "Netriplex", "value": "netriplex" },
  { "label": "NMU AB", "value": "nmu_ab" },
  { "label": "Nominum", "value": "nominum" },
  { "label": "NSOne", "value": "nsone" },
  { "label": "pointHQ", "value": "pointhq" },
  { "label": "Ports IT", "value": "ports_it" },
  { "label": "Prolexic DNS", "value": "prolexic_dns" },
  { "label": "RackSpace DNS", "value": "rackspace_dns" },
  { "label": "Return Path", "value": "return_path" },
  { "label": "Riktad AB", "value": "riktad_ab" },
  { "label": "Route 53", "value": "route_53" },
  { "label": "Sprint", "value": "sprint" },
  { "label": "Svenska domaner", "value": "svenska_domaner" },
  { "label": "TDC", "value": "tdc" },
  { "label": "UltraDns", "value": "ultradns" },
  { "label": "Verisign", "value": "verisign" },
  { "label": "WorldwideDNS", "value": "worldwidedns" },
  { "label": "Zerigo", "value": "zerigo" },
  { "label": "ZoneEdit", "value": "zoneedit" },
  { "label": "1shoppingcart", "value": "1shoppingcart" },
  { "label": "3D cart", "value": "3d_cart" },
  { "label": "Amazon Webstore", "value": "amazon_webstore" },
  { "label": "AmeriCommerce", "value": "americommerce" },
  { "label": "Ascentium Commerce Server", "value": "ascentium_commerce_server" },
  { "label": "AspDotNetStorefront", "value": "aspdotnetstorefront" },
  { "label": "ATG Commerce", "value": "atg_commerce" },
  { "label": "BigCartel", "value": "bigcartel" },
  { "label": "BigCommerce", "value": "bigcommerce" },
  { "label": "BorderFree", "value": "borderfree" },
  { "label": "Boxever", "value": "boxever" },
  { "label": "Branding Brand", "value": "branding_brand" },
  { "label": "Canal", "value": "canal" },
  { "label": "Cleverbridge", "value": "cleverbridge" },
  { "label": "Coinbase", "value": "coinbase" },
  { "label": "CoreCommerce", "value": "corecommerce" },
  { "label": "CS Cart", "value": "cs_cart" },
  { "label": "CubeCart", "value": "cubecart" },
  { "label": "Demandware", "value": "demandware" },
  { "label": "Ecwid", "value": "ecwid" },
  { "label": "EKM Powershop", "value": "ekm_powershop" },
  { "label": "Engagedly", "value": "engagedly" },
  { "label": "Epages", "value": "epages" },
  { "label": "Frosmo", "value": "frosmo" },
  { "label": "GoECart", "value": "goecart" },
  { "label": "GSI (Ebay Enterprise)", "value": "gsi_ebay_enterprise" },
  { "label": "Hybris (SAP)", "value": "hybris_sap" },
  { "label": "IBM Websphere", "value": "ibm_websphere" },
  { "label": "InSales", "value": "insales" },
  { "label": "Intershop", "value": "intershop" },
  { "label": "JTL-Shop 3", "value": "jtl_shop_3" },
  { "label": "Kalio", "value": "kalio" },
  { "label": "KonaKart", "value": "konakart" },
  { "label": "Mad Mobile", "value": "mad_mobile" },
  { "label": "Magento", "value": "magento" },
  { "label": "Magento Enterprise", "value": "magento_enterprise" },
  { "label": "Marketlive", "value": "marketlive" },
  { "label": "Miva Merchant", "value": "miva_merchant" },
  { "label": "Mobify", "value": "mobify" },
  { "label": "Moovweb", "value": "moovweb" },
  { "label": "Mozu", "value": "mozu" },
  { "label": "MyCommerce", "value": "mycommerce" },
  { "label": "NetSuite E-commerce", "value": "netsuite_e_commerce" },
  { "label": "OpenCart", "value": "opencart" },
  { "label": "osCommerce", "value": "oscommerce" },
  { "label": "Oxid", "value": "oxid" },
  { "label": "PINNACLE CART", "value": "pinnacle_cart" },
  { "label": "Pixafy", "value": "pixafy" },
  { "label": "Premium Web Cart", "value": "premium_web_cart" },
  { "label": "Prom.ua", "value": "prom_ua" },
  { "label": "SalonBiz / SpaBiz", "value": "salonbiz_spabiz" },
  { "label": "SEOshop", "value": "seoshop" },
  { "label": "Shopify", "value": "shopify" },
  { "label": "Shopp", "value": "shopp" },
  { "label": "ShopVisible", "value": "shopvisible" },
  { "label": "Shopware", "value": "shopware" },
  { "label": "Spree", "value": "spree" },
  { "label": "Squarespace ECommerce", "value": "squarespace_ecommerce" },
  { "label": "Tictail", "value": "tictail" },
  { "label": "UltraCart", "value": "ultracart" },
  { "label": "UniteU", "value": "uniteu" },
  { "label": "Upshot Commerce", "value": "upshot_commerce" },
  { "label": "Usablenet", "value": "usablenet" },
  { "label": "Venda", "value": "venda" },
  { "label": "Virtuemart", "value": "virtuemart" },
  { "label": "Visualsoft", "value": "visualsoft" },
  { "label": "Volusion", "value": "volusion" },
  { "label": "Vtex", "value": "vtex" },
  { "label": "WebLinc", "value": "weblinc" },
  { "label": "Woo Commerce", "value": "woo_commerce" },
  { "label": "WP eCommerce", "value": "wp_ecommerce" },
  { "label": "X-Cart", "value": "x_cart" },
  { "label": "Xt-commerce", "value": "xt_commerce" },
  { "label": "Yahoo Store", "value": "yahoo_store" },
  { "label": "Zoovy", "value": "zoovy" },

  { "label": "PrestaShop", "value": "prestashop" },
  { "label": "Magento 1.7", "value": "magento_1_7" },
  { "label": "Magento 1.8", "value": "magento_1_8" },
  { "label": "Magento 1.9", "value": "magento_1_9" },
  { "label": "Magento 2.0", "value": "magento_2_0" },
  { "label": "Magento 2 Community", "value": "magento_2_community" },
  { "label": "Magento 2 Enterprise", "value": "magento_2_enterprise" },
  { "label": "Shopify Plus", "value": "shopify_plus" },
  { "label": "Shopify Product Reviews", "value": "shopify_product_reviews" },
  { "label": "Salla", "value": "salla" },

  { "label": "Barilliance", "value": "barilliance" },
  { "label": "Candid", "value": "candid" },
  { "label": "Celerant", "value": "celerant" },
  { "label": "Channel Advisor", "value": "channel_advisor" },
  { "label": "Channel Intelligence by Google", "value": "channel_intelligence_by_google" },
  { "label": "ChannelAdvisor", "value": "channeladvisor" },
  { "label": "Etsy", "value": "etsy" },
  { "label": "FanPlayr", "value": "fanplayr" },
  { "label": "Forewards", "value": "forewards" },
  { "label": "Google Analytics Ecommerce Tracking", "value": "google_analytics_ecommerce_tracking" },
  { "label": "Google Trusted Stores", "value": "google_trusted_stores" },
  { "label": "Hook MyVisit", "value": "hook_myvisit" },
  { "label": "HookLogic", "value": "hooklogic" },
  { "label": "Insparq", "value": "insparq" },
  { "label": "Jirafe", "value": "jirafe" },
  { "label": "JustUno", "value": "justuno" },
  { "label": "Lengow", "value": "lengow" },
  { "label": "Lexity", "value": "lexity" },
  { "label": "Mercent", "value": "mercent" },
  { "label": "Nextopia", "value": "nextopia" },
  { "label": "Nosto", "value": "nosto" },
  { "label": "Octane", "value": "octane" },
  { "label": "OneStop", "value": "onestop" },
  { "label": "Reflektion", "value": "reflektion" },
  { "label": "Scene7", "value": "scene7" },
  { "label": "SearchSpring", "value": "searchspring" },
  { "label": "Site Vibes", "value": "site_vibes" },
  { "label": "SociableLabs", "value": "sociablelabs" },
  { "label": "Symphony Commerce", "value": "symphony_commerce" },
  { "label": "TheFind", "value": "thefind" },
  { "label": "WebEngage", "value": "webengage" },
  { "label": "Where2getit", "value": "where2getit" },
  { "label": "Yotpo", "value": "yotpo" },
  { "label": "AAHA Accredited", "value": "aaha_accredited" },
  { "label": "Absorb", "value": "absorb" },
  { "label": "Active Network (Active Educate)", "value": "active_network_active_educate" },
  { "label": "Aeries", "value": "aeries" },
  { "label": "ANGEL LMS", "value": "angel_lms" },
  { "label": "Aspen", "value": "aspen" },
  { "label": "Blackboard LMS", "value": "blackboard_lms" },
  { "label": "Canvas by Instructure", "value": "canvas_by_instructure" },
  { "label": "Capita-SIMS", "value": "capita_sims" },
  { "label": "Champions Way", "value": "champions_way" },
  { "label": "Compliance Wire", "value": "compliance_wire" },
  { "label": "CourseSites by Blackboard", "value": "coursesites_by_blackboard" },
  { "label": "Desire2Learn / Brightspace", "value": "desire2learn_brightspace" },
  { "label": "Docebo", "value": "docebo" },
  { "label": "Echo 360", "value": "echo_360" },
  { "label": "Edupoint", "value": "edupoint" },
  { "label": "Elucidat", "value": "elucidat" },
  { "label": "Follett Aspen", "value": "follett_aspen" },
  { "label": "Infinite Campus", "value": "infinite_campus" },
  { "label": "Its Learning LMS", "value": "its_learning_lms" },
  { "label": "Litmos", "value": "litmos" },
  { "label": "Moodle", "value": "moodle" },
  { "label": "MyBigCampus", "value": "mybigcampus" },
  { "label": "Rediker (Plus Portals)", "value": "rediker_plus_portals" },
  { "label": "REnWeb", "value": "renweb" },
  { "label": "Schoology", "value": "schoology" },
  { "label": "Senior Systems", "value": "senior_systems" },
  { "label": "StudyWiz", "value": "studywiz" },
  { "label": "SunGard K12 eSchool Plus", "value": "sungard_k12_eschool_plus" },
  { "label": "Tegrity", "value": "tegrity" },
  { "label": "Tyler Technologies", "value": "tyler_technologies" },
  { "label": "Veracross", "value": "veracross" },

  { "label": "Amazon SES", "value": "amazon_ses" },
  { "label": "BriteVerify", "value": "briteverify" },
  { "label": "CritSend", "value": "critsend" },
  { "label": "DynECT", "value": "dynect" },
  { "label": "ElasticEmail", "value": "elasticemail" },
  { "label": "Mailchimp Mandrill", "value": "mailchimp_mandrill" },
  { "label": "MailJet", "value": "mailjet" },
  { "label": "MessageBus", "value": "messagebus" },
  { "label": "MySMTP", "value": "mysmtp" },
  { "label": "Oracle SPF", "value": "oracle_spf" },
  { "label": "PostageApp", "value": "postageapp" },
  { "label": "Postmark", "value": "postmark" },
  { "label": "Rackspace MailGun", "value": "rackspace_mailgun" },
  { "label": "Sendgrid", "value": "sendgrid" },
  { "label": "SMTP.com", "value": "smtp_com" },
  { "label": "SocketLabs", "value": "socketlabs" },
  { "label": "SparkPost", "value": "sparkpost" },
  { "label": "TurboSMTP", "value": "turbosmtp" },

  { "label": "Adestra", "value": "adestra" },
  { "label": "AgilOne", "value": "agilone" },
  { "label": "AWeber", "value": "aweber" },
  { "label": "Biz Wizard", "value": "biz_wizard" },
  { "label": "Bluehornet", "value": "bluehornet" },
  { "label": "Boomtrain", "value": "boomtrain" },
  { "label": "Bronto", "value": "bronto" },
  { "label": "CakeMail", "value": "cakemail" },
  { "label": "Campaigner", "value": "campaigner" },
  { "label": "CampaignMonitor", "value": "campaignmonitor" },
  { "label": "Carma Mail (Compost Marketing)", "value": "carma_mail_compost_marketing" },
  { "label": "CheetahMail", "value": "cheetahmail" },
  { "label": "Communicator", "value": "communicator" },
  { "label": "Constant Contact", "value": "constant_contact" },
  { "label": "Customer.IO", "value": "customer_io" },
  { "label": "Delivra", "value": "delivra" },
  { "label": "dotMailer", "value": "dotmailer" },
  { "label": "ECircle (Teradata)", "value": "ecircle_teradata" },
  { "label": "Email Attitude (1000mercis)", "value": "email_attitude_1000mercis" },
  { "label": "Email Center Pro", "value": "email_center_pro" },
  { "label": "EmailDirect", "value": "emaildirect" },
  { "label": "Emarsys", "value": "emarsys" },
  { "label": "Ematch", "value": "ematch" },
  { "label": "Emma", "value": "emma" },
  { "label": "Eperflex / ividence", "value": "eperflex_ividence" },
  { "label": "ExactTarget", "value": "exacttarget" },
  { "label": "Fishbowl", "value": "fishbowl" },
  { "label": "Get-a-newsletter", "value": "get_a_newsletter" },
  { "label": "GetResponse", "value": "getresponse" },
  { "label": "Graphicmail", "value": "graphicmail" },
  { "label": "iContact", "value": "icontact" },
  { "label": "Klaviyo", "value": "klaviyo" },
  { "label": "Listrak", "value": "listrak" },
  { "label": "Liveclicker", "value": "liveclicker" },
  { "label": "Lyris", "value": "lyris" },
  { "label": "Mad Mimi", "value": "mad_mimi" },
  { "label": "MailChimp", "value": "mailchimp" },
  { "label": "Maildirect.se", "value": "maildirect_se" },
  { "label": "MailUp", "value": "mailup" },
  { "label": "Maropost", "value": "maropost" },
  { "label": "MessageGears", "value": "messagegears" },
  { "label": "Mojn", "value": "mojn" },
  { "label": "MultiNet", "value": "multinet" },
  { "label": "Nudgespot", "value": "nudgespot" },
  { "label": "Paloma", "value": "paloma" },
  { "label": "Predictive Response", "value": "predictive_response" },
  { "label": "Pure360", "value": "pure360" },
  { "label": "Remintrex", "value": "remintrex" },
  { "label": "Responsys", "value": "responsys" },
  { "label": "Sare", "value": "sare" },
  { "label": "SendInBlue", "value": "sendinblue" },
  { "label": "Silverpop", "value": "silverpop" },
  { "label": "SmarterRemarketer", "value": "smarterremarketer" },
  { "label": "SmartFocus", "value": "smartfocus" },
  { "label": "Stream Send", "value": "stream_send" },
  { "label": "Tedemis", "value": "tedemis" },
  { "label": "TriggerMail", "value": "triggermail" },
  { "label": "Trumpia", "value": "trumpia" },
  { "label": "Vero", "value": "vero" },
  { "label": "Vision6", "value": "vision6" },
  { "label": "WhatCounts / Publicaster", "value": "whatcounts_publicaster" },
  { "label": "YesMail", "value": "yesmail" },
  { "label": "Atmail", "value": "atmail" },
  { "label": "Ceryx", "value": "ceryx" },
  { "label": "Frontbridge", "value": "frontbridge" },
  { "label": "Gmail", "value": "gmail" },
  { "label": "GMX", "value": "gmx" },
  { "label": "Horde", "value": "horde" },
  { "label": "Hotmail", "value": "hotmail" },
  { "label": "Hushmail", "value": "hushmail" },
  { "label": "Inbox.com", "value": "inbox_com" },
  { "label": "IntY MailDefender", "value": "inty_maildefender" },
  { "label": "Lavabit", "value": "lavabit" },
  { "label": "Microsoft Email Providers", "value": "microsoft_email_providers" },
  { "label": "Mimecast", "value": "mimecast" },
  { "label": "MX Logic", "value": "mx_logic" },
  { "label": "Oracle Email Server", "value": "oracle_email_server" },
  { "label": "Outlook", "value": "outlook" },
  { "label": "Postini", "value": "postini" },
  { "label": "Rackspace Email", "value": "rackspace_email" },
  { "label": "Roundcube Email", "value": "roundcube_email" },
  { "label": "SquirrelMail", "value": "squirrelmail" },
  { "label": "Webmail", "value": "webmail" },
  { "label": "Yahoo Mail", "value": "yahoo_mail" },
  { "label": "Zimbra", "value": "zimbra" },
  { "label": "Zoho Email", "value": "zoho_email" },

  { "label": "ActiveNetwork", "value": "activenetwork" },
  { "label": "BusyConf", "value": "busyconf" },
  { "label": "Centium Software", "value": "centium_software" },
  { "label": "Certain Software", "value": "certain_software" },
  { "label": "CompuSystems", "value": "compusystems" },
  { "label": "Cvent", "value": "cvent" },
  { "label": "ePly Events", "value": "eply_events" },
  { "label": "etouches", "value": "etouches" },
  { "label": "Eventbrite", "value": "eventbrite" },
  { "label": "EventsAir by Centium", "value": "eventsair_by_centium" },
  { "label": "Experient", "value": "experient" },
  { "label": "Expotracker", "value": "expotracker" },
  { "label": "Info Salons", "value": "info_salons" },
  { "label": "RegOnline", "value": "regonline" },
  { "label": "Regpacks", "value": "regpacks" },
  { "label": "SignUp4", "value": "signup4" },
  { "label": "Ungerboeck Software", "value": "ungerboeck_software" },
  { "label": "Ticket Tailor", "value": "ticket_tailor" },
  { "label": "Weezevent", "value": "weezevent" },
  { "label": "ShowClix", "value": "showclix" },
  { "label": "See Tickets", "value": "see_tickets" },
  { "label": "Ticket Spice", "value": "ticket_spice" },
  { "label": "Etix", "value": "etix" },

  { "label": "Adobe Edge", "value": "adobe_edge" },
  { "label": "Cufon", "value": "cufon" },
  { "label": "FontDeck", "value": "fontdeck" },
  { "label": "Fonts.com", "value": "fonts_com" },
  { "label": "Google Font API", "value": "google_font_api" },
  { "label": "Typekit", "value": "typekit" },

  { "label": "1001menus", "value": "1001menus" },
  { "label": "BeyondMenu", "value": "beyondmenu" },
  { "label": "Brygid", "value": "brygid" },
  { "label": "Caviar", "value": "caviar" },
  { "label": "DoorDash", "value": "doordash" },
  { "label": "GrubHub", "value": "grubhub" },
  { "label": "MyPizza.com", "value": "mypizza_com" },
  { "label": "OrderAhead", "value": "orderahead" },
  { "label": "OrderingOnline", "value": "orderingonline" },
  { "label": "Seamless Web", "value": "seamless_web" },

  { "label": "Android", "value": "android" },
  { "label": "AngularJS", "value": "angularjs" },
  { "label": "AngularJS 1.2.20", "value": "angularjs_1_2_20" },
  { "label": "AngularJS 1.3.0 Beta", "value": "angularjs_1_3_0_beta" },
  { "label": "Apache Coyote", "value": "apache_coyote" },
  { "label": "Apache Coyote v1.1", "value": "apache_coyote_v1_1" },
  { "label": "ASP.NET", "value": "asp_net" },
  { "label": "Django", "value": "django" },
  { "label": "Elixir", "value": "elixir" },
  { "label": "Express JS Framework", "value": "express_js_framework" },
  { "label": "Phoenix", "value": "phoenix" },
  { "label": "PHP", "value": "php" },
  { "label": "PHP 5.3", "value": "php_5_3" },
  { "label": "PrototypeJS", "value": "prototypejs" },
  { "label": "Ruby On Rails", "value": "ruby_on_rails" },
  { "label": "Scala", "value": "scala" },
  { "label": "Microsoft.net", "value": "microsoft_net" },
  { "label": "Go Framework", "value": "go_framework" },
  { "label": "React Native", "value": "react_native" },
  { "label": "Node.js", "value": "node_js" },
  { "label": "Xamarin", "value": "xamarin" },
  { "label": "F#", "value": "f" },

  { "label": "Domo", "value": "domo" },
  { "label": "Qlik Sense", "value": "qlik_sense" },
  { "label": "Sigma", "value": "sigma" },

  { "label": "Avaya", "value": "avaya" },
  { "label": "Mitel", "value": "mitel" },

  { "label": "Frame.io", "value": "frame_io" },
  { "label": "ServiceNow", "value": "servicenow" },
  { "label": "Insperity", "value": "insperity" },
  { "label": "PEO", "value": "peo" },
  { "label": "Trinet", "value": "trinet" },
  { "label": "Gusto", "value": "gusto" },
  { "label": "Justworks", "value": "justworks" },

  { "label": "Highspot", "value": "highspot" },
  { "label": "Seismic", "value": "seismic" },

  { "label": "CMiC", "value": "cmic" },
  { "label": "Procore", "value": "procore" },
  { "label": "Viewpoint", "value": "viewpoint" },

  { "label": "Azure Devops", "value": "azure_devops" },
  { "label": "Automation Anywhere", "value": "automation_anywhere" },
  { "label": "Uipath", "value": "uipath" },
  { "label": "Jamf", "value": "jamf" }
,
  { "label": "123ContactForm", "value": "123contactform" },
  { "label": "Confirmit", "value": "confirmit" },
  { "label": "Formassembly", "value": "formassembly" },
  { "label": "Forms on the Fly", "value": "forms_on_the_fly" },
  { "label": "Formsite", "value": "formsite" },
  { "label": "Formspree", "value": "formspree" },
  { "label": "Formstack", "value": "formstack" },
  { "label": "Gravity Forms", "value": "gravity_forms" },
  { "label": "Jotform", "value": "jotform" },
  { "label": "Podio", "value": "podio" },
  { "label": "Wufoo", "value": "wufoo" },

  { "label": "3t Systems", "value": "3t_systems" },
  { "label": "6 Degrees Hosting", "value": "6_degrees_hosting" },
  { "label": "A Small Orange", "value": "a_small_orange" },
  { "label": "Amazon AWS", "value": "amazon_aws" },
  { "label": "DigitalOcean", "value": "digitalocean" },
  { "label": "Google Cloud Hosting", "value": "google_cloud_hosting" },
  { "label": "Heroku", "value": "heroku" },
  { "label": "Hostgator", "value": "hostgator" },
  { "label": "Hostinger", "value": "hostinger" },
  { "label": "OVH", "value": "ovh" },
  { "label": "Rackspace", "value": "rackspace" },

  { "label": "Apache", "value": "apache" },
  { "label": "Nginx", "value": "nginx" },
  { "label": "Varnish", "value": "varnish" },
  { "label": "Ubuntu", "value": "ubuntu" },

  { "label": "CloudFlare", "value": "cloudflare" },
  { "label": "Incapsula", "value": "incapsula" },

  { "label": "New Relic", "value": "new_relic" },
  { "label": "Pingdom", "value": "pingdom" },

  { "label": "Zoom Webinar", "value": "zoom_webinar" },
  { "label": "Webex", "value": "webex" },

  { "label": "YouTube", "value": "youtube" },
  { "label": "Vimeo", "value": "vimeo" },

  { "label": "Stripe", "value": "stripe" },
  { "label": "Paypal", "value": "paypal" },

  { "label": "Shopify", "value": "shopify" },
  { "label": "Woo Commerce", "value": "woo_commerce" },

  { "label": "WordPress.org", "value": "wordpress_org" },
  { "label": "Wix", "value": "wix" },

  { "label": "React", "value": "react" },
  { "label": "AngularJS", "value": "angularjs" }

]